# Generated by Django 2.1.2 on 2019-04-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_auto_20190411_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='entity',
            field=models.CharField(default='Student', max_length=200),
        ),
    ]
