# Generated by Django 2.1.2 on 2019-04-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0003_entity_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
    ]
