# Generated by Django 2.1.2 on 2019-04-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0004_login_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='rollno',
            field=models.CharField(default='', max_length=200),
        ),
    ]
