# Generated by Django 2.1.2 on 2019-04-13 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0008_auto_20190412_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExamName', models.CharField(max_length=200)),
                ('question', models.CharField(max_length=1000)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.Departments')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.Course')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.Subjects')),
            ],
        ),
        migrations.CreateModel(
            name='marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.IntegerField(default=0)),
                ('marks', models.IntegerField(default=0)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.Subjects')),
            ],
        ),
    ]
