# Generated by Django 2.1.2 on 2019-04-13 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0010_auto_20190413_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.IntegerField(default=0)),
                ('marks', models.IntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.exam')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.Subjects')),
            ],
        ),
    ]
